#! /bin/sh
echo "// -------------------------------------------------------------------"
echo "// Author: lfwu"
echo "// Date:" `date +"%B-%d-%Y"`
echo "// Note:"
echo "// Email:zgwulongfei@gmail.com"
echo "// Blog:http://blog.csdn.net/hackmind"
echo "// -------------------------------------------------------------------"
echo "#include <iostream>"
echo "using namespace std;"
printf "\n"
echo "int"
echo "main(int argc, char** argv){"
printf "\n"
echo "}"
