include ../../base/Make.Defines

CXXPROGS= 4.13.1 4.13.2 4.13.3 4.13.4 4.13.5 4.13.6 4.13.7 4.13.8 4.13.9 4.13.10 

all:${CXXPROGS}




4.13.1:4.13.1.o 
	${CXX} ${CXXFLAGS} -o $@ $<
4.13.2:4.13.2.o 
	${CXX} ${CXXFLAGS} -o $@ $<
4.13.3:4.13.3.o 
	${CXX} ${CXXFLAGS} -o $@ $<
4.13.4:4.13.4.o 
	${CXX} ${CXXFLAGS} -o $@ $<
4.13.5:4.13.5.o 
	${CXX} ${CXXFLAGS} -o $@ $<
4.13.6:4.13.6.o 
	${CXX} ${CXXFLAGS} -o $@ $<
4.13.7:4.13.7.o 
	${CXX} ${CXXFLAGS} -o $@ $<
4.13.8:4.13.8.o 
	${CXX} ${CXXFLAGS} -o $@ $<
4.13.9:4.13.9.o 
	${CXX} ${CXXFLAGS} -o $@ $<
4.13.10:4.13.10.o 
	${CXX} ${CXXFLAGS} -o $@ $<
clean:
	rm -f -r *.o ${CXXPROGS}
