include ../../base/Make.Defines

CXXPROGS= arrayone nullChar string instr1 instr2 instr3 numstr strtype1 strtype2 strtype3 strRaw UTFchar structur assgn_st arrstruc address pointer use_new arraynew addpntrs ptrstr newstrct delete mixtypes choices 

all:${CXXPROGS}




arrayone:arrayone.o 
	${CXX} ${CXXFLAGS} -o $@ $<
nullChar:nullChar.o 
	${CXX} ${CXXFLAGS} -o $@ $<
string:string.o 
	${CXX} ${CXXFLAGS} -o $@ $<
instr1:instr1.o 
	${CXX} ${CXXFLAGS} -o $@ $<
instr2:instr2.o 
	${CXX} ${CXXFLAGS} -o $@ $<
instr3:instr3.o 
	${CXX} ${CXXFLAGS} -o $@ $<
numstr:numstr.o 
	${CXX} ${CXXFLAGS} -o $@ $<
strtype1:strtype1.o 
	${CXX} ${CXXFLAGS} -o $@ $<
strtype2:strtype2.o 
	${CXX} ${CXXFLAGS} -o $@ $<
strtype3:strtype3.o 
	${CXX} ${CXXFLAGS} -o $@ $<
strRaw:strRaw.o 
	${CXX} ${CXXFLAGS} -o $@ $<
UTFchar:UTFchar.o 
	${CXX} ${CXXFLAGS} -o $@ $<
structur:structur.o 
	${CXX} ${CXXFLAGS} -o $@ $<
assgn_st:assgn_st.o 
	${CXX} ${CXXFLAGS} -o $@ $<
arrstruc:arrstruc.o 
	${CXX} ${CXXFLAGS} -o $@ $<
address:address.o 
	${CXX} ${CXXFLAGS} -o $@ $<
pointer:pointer.o 
	${CXX} ${CXXFLAGS} -o $@ $<
use_new:use_new.o 
	${CXX} ${CXXFLAGS} -o $@ $<
arraynew:arraynew.o 
	${CXX} ${CXXFLAGS} -o $@ $<
addpntrs:addpntrs.o 
	${CXX} ${CXXFLAGS} -o $@ $<
ptrstr:ptrstr.o 
	${CXX} ${CXXFLAGS} -o $@ $<
newstrct:newstrct.o 
	${CXX} ${CXXFLAGS} -o $@ $<
delete:delete.o 
	${CXX} ${CXXFLAGS} -o $@ $<
mixtypes:mixtypes.o 
	${CXX} ${CXXFLAGS} -o $@ $<
choices:choices.o 
	${CXX} ${CXXFLAGS} -o $@ $<
clean:
	rm -f -r *.o ${CXXPROGS}
