include ../../Make.Defines

CXXPROGS= exercise-371 exercise-372 exercise-373 \
	exercise-374 exercise-375

all:${CXXPROGS}

exercise-371:exercise-371.o
	${CXX} ${CXXFLAGS} -o $@ $<

exercise-372:exercise-372.o
	${CXX} ${CXXFLAGS} -o $@ $<

exercise-373:exercise-373.o
	${CXX} ${CXXFLAGS} -o $@ $<

exercise-374:exercise-374.o
	${CXX} ${CXXFLAGS} -o $@ $<

exercise-375:exercise-375.o
	${CXX} ${CXXFLAGS} -o $@ $<

clean:
	rm -f -r *.o ${CXXPROGS}

